spring:
  datasource:
    url: >
      jdbc:mysql://localhost:3306/persons_app_db?createDatabaseIfNotExist=true
      &useSSL=false&serverTimezone=UTC&useUnicode=true
      &useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: developer
    password: developer
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    rest:
      base-path: /api

server:
  error:
    include-stacktrace: never
    include-message: always
  port: 8000
